### ISSUE TITLE
Feature request: `as` prop

### ISSUE THREAD

**Issue by incompletude** [bikk-uk/react-css-grid#37]
It would be nice to have an `as` to choose the html tag.

I saw the types for `DivProps` being used so this feature could make a mess, not sure how to do it.

Nice lib, thx.

**Comment by aboyce** [comment]
Hello @incompletude,

Apologies in the delay in responding to you on this.

@stovv did an implementation of this over at the **react-css-flex** repo via this [PR 47](https://github.com/bikk-uk/react-css-flex/pull/47). I think this covers what you are asking for and it would be good to keep the two libraries in sync feature wise.

I'll implement those changes in this repository and get a release pushed out.

Thanks for raising the issue 😀

**Comment by aboyce** [comment]
Changes have been done as part of [PR-38](https://github.com/bikk-uk/react-css-grid/pull/38)

**Comment by aboyce** [comment]
This was published in [v1.5.0](https://github.com/bikk-uk/react-css-grid/releases/tag/1.5.0)
