### ISSUE TITLE
v2 still works with React v17

### ISSUE THREAD

**Issue by curtvict** [bikk-uk/react-css-grid#43]
Is there some reason I'm missing that we couldn't be more permissive with the dependency versions [here](https://github.com/bikk-uk/react-css-grid/blob/master/package.json#L62-L63)? It would be great if I could avoid pinning `react` and `react-dom` in my package resolutions and continue to use `react-css-grid` and `react-css-flex`, since they both should still work in versions of React lower than v18.

Maybe we could update the dependencies to

```json
  "dependencies": {
    "react": ">=17.0.0",
    "react-dom": ">=17.0.0"
  },
```

I'm happy to open this PR for you in both repositories if you agree with the change.

**Comment by curtvict** [comment]
Or, perhaps adopting a peerDependency resolution like react-query just did might be best. Upgrading to this version did not bump my internal version of react and was compatible as a patch on their end:

https://github.com/aaronshaf/react-toggle/pull/176/files

**Comment by aboyce** [comment]
Hello @curtvict,

Thanks for the suggestion, and examples, I think it makes a lot of sense.

I've had a play about with it and seems to work as expected for me in a test project, I do get a warning but that seems to go when you do a full install. The peer dependencies seem like the cleanest suggestion, I did go with a syntax that another React component library use as it feels a bit more explicit [Semantic UI](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/package.json#L189-L190).

I'll roll this out across the libraries, if you have any issues with it let me know.

Thanks 😀

**Comment by curtvict** [comment]
> I do get a warning but that seems to go when you do a full install

Yep. That should be expected. A peer dependency addition will warn the user that there is a dependency unmet in their project. In this case your library requires React & React DOM to run, so this warning is valid and likely won't be seen by anyone unless they're trying to use the library in a non-React project for whatever reason.

Thanks so much for these libraries, by they way. They've really helped us solve the layout problem of our design system and allow us to quickly create grid systems on demand. Kudos to you!

**Comment by aboyce** [comment]
These have both been published now, seem to be working well for me in a test project.

Thank you for your help and the feedback, much appreciated, I'm glad they are helping you out 😊

**Comment by curtvict** [comment]
Thanks @aboyce! Everything seems to be looking good on our end as well!
