### ISSUE TITLE
Reliability

### ISSUE THREAD

**Issue by scottpageindysoft** [bikk-uk/react-css-grid#46]
Is this being maintained?

Maybe CSS grid hasn't changed much in the past 10 months to prompt an update.
I don't want to start using something that needs to be replaced soon after.

If it's not being maintained, it would be great to know, so I can fork and continue to use it.

Thanks!

**Comment by aboyce** [comment]
Hello @scottpageindysoft,

I think CSS Grid is pretty stable now yeah, I've not had any issues raised to suggest that it needs updating yet. But I agree it hasn't been touched in a long while, so I've put out a new version with some updated dependencies to give it refresh and give confidence all the pipelines/releases are still working should updates need to me made 😃 

So yeah, its still been maintained 😃 

Thanks,
Adam
